### ISSUE TITLE
can't vargant up 

### ISSUE THREAD

**Issue by HimaTaha** [udacity/fullstack-nanodegree-vm#64]
C:\Users\Hima\fullstack>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
    default:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/Users/Hima/fullstack/base

any suggestions ?

**Comment by SteveWooding** [comment]
I think the issue is that you are not running the `vagrant up` command from the correct directory. You should be in the `vagrant` directory. Also, for logging into the Vagrant VM, it is best to run these commands from the Git Bash console, as the `ssh` command will need to be available in order to run `vagrant ssh`.
