### ISSUE TITLE
Unable to Vagrant Up on WIndows X, been looking for solution for over 3 months.

### ISSUE THREAD

**Issue by lg2696** [udacity/fullstack-nanodegree-vm#84]
I am getting the following Vagrant up errors, my OS is Windows 10, pls see screen shots attached.
![vagrantuperror20180122_vb](https://user-images.githubusercontent.com/31082820/35762033-231762ea-085e-11e8-89e5-26330c451b5c.JPG)

**Comment by karlud** [comment]
This usually indicates that the Vagrantfile in your current directory (the "FSND-Virtual-Machine/vagrant" directory) is one created by a broken "vagrant init" process. The sign of this is that it's trying to access an image called "base", which doesn't exist.

That Vagrantfile needs to be replaced with the one downloaded from the Classroom.

The correct Vagrantfile will refer to a box called "bento/ubuntu-16.04-i386" (or similar) rather than "base".

**Comment by lg2696** [comment]
I had the same problem with the classroom files I was instructed to use
originally and reinstalling them, but failed. My mentor said there is a
known problem with those versions and Windows10. He told me to install a
previous version of Vagrant & VB, it still did not work. I have tried so
many suggested solutions, none worked. Frustrated.

On Feb 3, 2018 2:10 AM, "Karl Krueger" <notifications@github.com> wrote:

This usually indicates that the Vagrantfile in your current directory (the
"FSND-Virtual-Machine/vagrant" directory) is one created by a broken
"vagrant init" process. The sign of this is that it's trying to access an
image called "base", which doesn't exist.

That Vagrantfile needs to be replaced with the one downloaded from the
Classroom.

The correct Vagrantfile will refer to a box called
"bento/ubuntu-16.04-i386" (or similar) rather than "base".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/udacity/fullstack-nanodegree-vm/issues/84#issuecomment-362786393>,
or mute the thread
